In [1]:
import numpy as np
import random

In [14]:
dic = {}

dic[(1,2)] = (3,4), 8

print(dic)

{(1, 2): ((3, 4), 8)}


In [20]:
class Grid:
    
    def __init__(self, para):
        # Create board of specifc board size 
        self.grid = np.zeros((para[0], para[0]), dtype=int)
        self.nest_value = 25
        self.food_source_value = 1000
        self.ant_value = 5
        self.pheromone_strength = para[1]
        self.pheromone_fade = para[2]
        self.ant_dict = {}
        self.nest_location = (0,0)

    # Get neighbour xy coordinates as tuple  
    def check_neighbours(self, coord, grid_size):
        # Initalize variables
        neighbours = []

        # List of relative position for all possible neighbours of a coordinate
        adj = [(-1, 1), (0, 1), (1, 1), (-1, 0), (1, 0), (-1, -1), (0,-1), (1,-1)]

        # Create list of all possible nieghbours
        for n in adj:
            neighbours.append(tuple(np.subtract(coord, n)))

        # In case of corners and edge pieces: find all neighbours that exist but are not valid for the specific board
        neigh = []
        for n_tup in neighbours:
            if n_tup[0] < 0 or n_tup[1] < 0:
                neigh.append(n_tup)
            elif n_tup[0] > grid_size or n_tup[1] > grid_size:
                neigh.append(n_tup)

        # Remove the found none valid neighbours 
        for i in neigh:
            neighbours.remove(i)

        # Return list of neighbours as tuple
        return neighbours

    # change value at specific cell, returns new grid
    def change_cell_value(self, coord, new_value):
        self.grid[coord[1]][coord[0]] = new_value
        return self.grid

    # return which value a cell has
    def get_kind(self, coord):
        return self.grid[coord[1]][coord[0]]
    
    def setKind(self, coord, value):
        x = coord[0]
        y = coord[1]
        if value is not 5 and value is not 25 and value < 100:
            return "Invalid value"
        self.grid[y, x] = value

    def antArrives(self, coord):
        x = coord[0]
        y = coord[1]
        self.grid[y, x] += self.ant_value

    def antLeaves(self, coord):
        x = coord[0]
        y = coord[1]
        self.grid[y, x] -= self.ant_value
        self.addPheromone(coord)

    def addPheromone(self, coord):
        x = coord[0]
        y = coord[1]
        self.grid[y, x] += pheromone_strength

    def pheromoneFade(self, coord):
        # The cell must already have pheromones
        x = coord[0]
        y = coord[1]
        self.grid[y, x] -= phereomone_fade

    def retrieveFood(self, coord):
        # The cell must be of the kind food source
        x = coord[0]
        y = coord[1]
        self.grid[y, x] -= self.food_value;
    
    def setNestLocation(self, coord):
        x = coord[0]
        y = coord[1]
        self.nest_location = (x,y)
        self.setKind(coord, self.nest_value)

    def setFoodSource(self, coord):
        x = coord[0]
        y = coord[1]
        self.setKind(coord, self.food_source_value)

    def origin_distance(self, coord, origin):
        val = np.square(coord[0]-origin[0])+np.square(coord[1]-origin[1])
        return np.sqrt(val)
        
    def possible_steps_list(self, coord, origin):
        pn = self.check_neighbours(coord)
        dist = self.origin_distance(coord, origin)
        
        best_neigh = []
        for n in pn:
            distance = self.origin_distance(n, origin)
            if distance > dist:
                best_neigh.append(n)
        return best_neigh
        
    def decide_step_worker(self, coord, origin):
        possible_steps = possible_steps_list(coord, origin)
        pos_step = []
        for p in possible_steps:
            if 0 < self.get_kind(p) <= 1:
                pos_step.append(p)
        
        if pos_step == []:
            pos_step = possible_steps
        
        pos_step_sum = pos_step.sum()
        probability_distribution = []
        
        for pos in pos_step:
            probability_distribution.append(self.get_kind(pos)/pos_step_sum)
            
        return choice(pos_step, 1, p=probability_distribution)
    
    def decide_step_search(self, coord, origin):
        possible_steps = self.possible_steps_list(coord, origin)
        return random.choice(possible_steps)
    
    def antSetStep(self, coord, nextCoord):
        x = coord[0]
        y = coord[1]
        x_next = nextCoord[0]
        y_next = nextCoord[1]
        self.grid[y_next, x_next] += self.ant_value
        self.grid[y, x] -= self.ant_value
        self.grid[y, x] += self.pheromone_strength
        # TODO Cost omhoog

    def routeBack(self, coord, origin):
        x = coord[0]
        y = coord[1]

        x_new = x
        y_new = y

        x_orig = origin[0]
        y_orig = origin[1]

        dx = x - x_orig
        dy = y - y_orig

        # Three possibilities: ant is on the same x or y coordinate, in which case it
        # can walk back in a straight line.
        # Or the x-distance is the same as the y-distance, in whcih case the ant can 
        # walk back in diagonal line.
        # Else, the ant should walk back in a partly diagonal, partly straight line.

        while x != x_orig and y != y_orig:
            if x == x_orig:
                x_new += dx / np.abs(dx)
                self.antSetStep((x, y), (x_new, y_new))
                x = x_new
                continue

            if np.abs(dx) == np.abs(dy):
                x_new += dx / np.abs(dx)
                y_new += dx / np.abs(dy)
                self.antSetStep((x, y), (x_new, y_new))
                x = x_new
                y = y_new
                continue

            while y != y_orig:
                x_new += dx / np.abs(dx)
                y_new += dx / np.abs(dy)
                self.antSetStep((x, y), (x_new, y_new))
                x = x_new
                y = y_new

            y_new += dy / np.abs(dy)
            self.antSetStep((x, y), (x_new, y_new))
            y = y_new
            
    def add_work_ant(self):
        self.ant_dict[self.nest_location] = self.nest_location, 'w'
    
    def add_search_ant(self):
        self.ant_dict[self.nest_location] = self.nest_location, 's'
        
    def get_ant_origin(self, coord):
        self.ant_dict[coord]

    # update board
    def renew_board(self):
        current_board = self.grid
        
        for i in self.grid:
            for j in i:
                curr_cell = (j,i)
                cell_value = get_kind((j,i))
                
                # If cell is empty
                if cell_value == 0:
                    continue
                
                # If cell contains an ant
                if curr_cell in self.ant_dict.keys():
                    origin = self.ant_dict[curr_cell][0]
                    type_ant = self.ant_dict[curr_cell][1]
                    
                    # Check if worker ant
                    if type_ant == 'w':
                        new_cell = selfdecide_step_worker(curr_cell, origin)
                        self.antSetStep(coord, new_cell)
                    # Check if search ant
                    if type_ant == 's':
                        new_cell = selfdecide_step_search(curr_cell, origin)
                        self.antSetStep(coord, new_cell)
                        
                # If cell is empty but contains a pheromone
                if 0 < cell_value <= 1:
                    current_board.pheromoneFade(curr_cell)
                    
                # If cell contains a foodsource, change origin when there is also an ant and lower the amount of 
                # food left and lower cost
                if cell_value == 

                # If cell contains a nest, change origin when there is also an ant
                if cell_value == 
                
                    
            

    
world = Grid([8, 1, 2])

print(world.ant_dict)
#print(world.grid)
world.setNestLocation((3,4))
world.add_work_ant()
print(world.grid)
world.nest_location
print(type(world.ant_dict[(3,4)][1]))

{}
[[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0 25  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]]
<class 'str'>
